[ExcelFlow]
InputPaths   = ["a", "b"]
Namespace    = "HEE"
TemplatePath = "hello.template"
EndOfLine    = "LF" # LF | CRLF | ENVIRONMENT

[ExcelFlow.Codegen]
Output = "outdir"

[ExcelFlow.Sqlite]
Output = "a.db"
